### PR TITLE
feat: improved architecture diagram

### PR DESCRIPTION
**Pull request by liqwiz**

### CODE REVIEW

**Review by ramenforbreakfast — DISMISSED** [review]
LGTM!, one question, what exactly is the picture with "deleted/added" with the diagrams side by side? They look exactly the same and not sure why that is there.

**Comment by ramenforbreakfast** [comment]
Dismissing my approval as I have another gripe with the diagram. 

Technically, it is not just the `Collateral` contract that references the USDC BaseToken, but `StrategyController`, `Strategy`, and `Yield Farm`, since they will all be directly interacting with the USDC passing it up/down during deposit/withdraw.

**Review by ramenforbreakfast — APPROVED** [review]
LGTM, just confirming I see you removed that file I mentioned. Assuming that was indeed unnecessary to keep?

**Review by XavierEkkel — APPROVED** [review]
LGTM

**Comment by liqwiz** [comment]
> LGTM, just confirming I see you removed that file I mentioned. Assuming that was indeed unnecessary to keep?

Yep, current diff is fine

**Pull request merged**
